// src/constants/post.constants.ts
export const FETCH_POSTS_REQUEST = "FETCH_POSTS_REQUEST";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAILURE = "FETCH_POSTS_FAILURE";
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";
export const UNLIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";
